// ap3_pinmap.c
//
// Map of board pins to Artemis pad numbers
//
//What you see is what you get pin-to-pad on the Apollo3
const uint8_t ap3_pin2pad[] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    AP3_GPIO_PAD_UNUSED,    // SWDIO
    AP3_GPIO_PAD_UNUSED,    // SWDCK
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    AP3_GPIO_PAD_UNUSED, //The one pad not broken out of the Apollo3 on the Artemis
    31,
    32,
    AP3_GPIO_PAD_UNUSED,    // SWD
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    AP3_GPIO_PAD_UNUSED, //The one pad not broken out of the Apollo3 on the Artemis
    47,
    48,
    49,
};

//
// Pin object index table
//
STATIC const machine_pin_obj_t machine_pin_obj[] = {
    {{&machine_pin_type}, 0},
    {{&machine_pin_type}, 1},
    {{&machine_pin_type}, 2},
    {{&machine_pin_type}, 3},
    {{&machine_pin_type}, 4},
    {{&machine_pin_type}, 5},
    {{&machine_pin_type}, 6},
    {{&machine_pin_type}, 7},
    {{&machine_pin_type}, 8},
    {{&machine_pin_type}, 9},
    {{&machine_pin_type}, 10},
    {{&machine_pin_type}, 11},
    {{&machine_pin_type}, 12},
    {{&machine_pin_type}, 13},
    {{&machine_pin_type}, 14},
    {{&machine_pin_type}, 15},
    {{&machine_pin_type}, 16},
    {{&machine_pin_type}, 17},
    {{&machine_pin_type}, 18},
    {{&machine_pin_type}, 19},
    {{&machine_pin_type}, 20},
    {{&machine_pin_type}, 21},
    {{&machine_pin_type}, 22},
    {{&machine_pin_type}, 23},
    {{&machine_pin_type}, 24},
    {{&machine_pin_type}, 25},
    {{&machine_pin_type}, 26},
    {{&machine_pin_type}, 27},
    {{&machine_pin_type}, 28},
    {{&machine_pin_type}, 29},
    {{NULL},              30},  // Unused
    {{&machine_pin_type}, 31},
    {{&machine_pin_type}, 32},
    {{&machine_pin_type}, 33},
    {{&machine_pin_type}, 34},
    {{&machine_pin_type}, 35},
    {{&machine_pin_type}, 36},
    {{&machine_pin_type}, 37},
    {{&machine_pin_type}, 38},
    {{&machine_pin_type}, 39},
    {{&machine_pin_type}, 40},
    {{&machine_pin_type}, 41},
    {{&machine_pin_type}, 42},
    {{&machine_pin_type}, 43},
    {{&machine_pin_type}, 44},
    {{&machine_pin_type}, 45},
    {{NULL},              46},  // Unused
    {{&machine_pin_type}, 47},
    {{&machine_pin_type}, 48},
    {{&machine_pin_type}, 49},
};
